[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'vim-scripts/gtags.vim'

[[plugins]]
repo = 'zebult/auto-gtags.vim'

[[plugins]]
repo = 'vim-scripts/taglist.vim'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'vim-scripts/yanktmp.vim'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'arnaud-lb/vim-php-namespace'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'janko-m/vim-test'

[[plugins]]
repo = 'craigemery/vim-autotag'

[[plugins]]
repo = 'jwalton512/vim-blade'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'tomlion/vim-solidity'

#[[plugins]]
#repo = 'grohiro/vim-test-truffle'

[[plugins]]
repo = 'maralla/completor.vim'

[[plugins]]
repo = 'lvht/phpcd.vim'
build = 'composer install'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = '2072/PHP-Indenting-for-VIm'

[[plugins]]
repo = 'hashivim/vim-terraform'

[[plugins]]
repo = 'juliosueiras/vim-terraform-completion'
